Repository nimblehq/flutter-ic-kaung-thieu, pull requests merged in 2023-04, with the labels that each got.

#38 [#3] [Chore] Set up the CI with Fastlane and GitHub Actions
  .github/workflows/run_ci_staging.yml
Labels: type : chore, #ci-cd, @0.1.0

#37 [#4] [Chore] Set up the CD with Fastlane and GitHub Actions for iOS
  .github/workflows/ios_deploy_production.yml
  .github/workflows/ios_deploy_staging.yml
  .github/workflows/ios_deploy_to_app_store.yml
  .github/workflows/ios_deploy_to_testflight.yml
  .github/workflows/run_ci_staging.yml
  ios/.gitignore
  ios/Flutter/AppFrameworkInfo.plist
  ios/Gemfile.lock
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  ios/fastlane/Constants/Constants.rb
  ios/fastlane/Constants/Environments.rb
  ios/fastlane/Fastfile
Labels: type : chore, #ci-cd

#39 [Chore] Bump version to 0.2.0
  pubspec.yaml
Labels: type : chore

#42 [#32] [Chore] Set up the CD with Firebase and GitHub Actions for Android
  .github/workflows/android_deploy_production.yml
  .github/workflows/android_deploy_production_to_playstore.yml
  .github/workflows/android_deploy_staging.yml
  android/.gitignore
  android/app/build.gradle
  android/app/google-services.json
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
Labels: type : chore, #ci-cd, @0.2.0

#43 [#5] [UI] As a user, I can see the Splash screen
  assets/images/nimble_logo_white.png
  assets/images/splash_background.png
  integration_test/real_app_test.dart
  lib/main.dart
  lib/screens/login/login.dart
  lib/screens/splash/splash.dart
Labels: type : feature, #general, @0.2.0

#45 [Chore] Bump version to 0.3.0
  pubspec.yaml
Labels: type : chore

#44 Release - 0.2.0
  .github/workflows/android_deploy_production.yml
  .github/workflows/android_deploy_production_to_playstore.yml
  .github/workflows/android_deploy_staging.yml
  android/.gitignore
  android/app/build.gradle
  android/app/google-services.json
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
  assets/images/nimble_logo_white.png
  assets/images/splash_background.png
  integration_test/real_app_test.dart
  lib/main.dart
  lib/screens/login/login.dart
  lib/screens/splash/splash.dart
  pubspec.yaml
Labels: type : release, @0.2.0

#49 [#9] [Feature] [Part 1] Backend implementation for sign in
  android/app/build.gradle
  lib/api/api_service.dart
  lib/api/exception/network_exceptions.dart
  lib/api/repository/login_repository.dart
  lib/di/provider/dio_provider.dart
  lib/main.dart
  lib/model/request/login_request.dart
  lib/model/response/login_attributes_response.dart
  lib/model/response/login_response.dart
  lib/screens/login/login_screen.dart
  lib/screens/splash/splash.dart
  pubspec.lock
  pubspec.yaml
  test/api/repository/login_repository_test.dart
  test/mocks/mock_util.dart
Labels: type : feature, #authentication, @0.3.0

#48 [#6] [UI] As a user, I can sign in with email and password
  integration_test/my_home_page_test.dart
  ios/Podfile.lock
  lib/l10n/app_en.arb
  lib/main.dart
  lib/screens/login/login_form.dart
  lib/screens/login/login_screen.dart
  lib/screens/splash/splash.dart
  lib/screens/widgets/blur_image.dart
  lib/screens/widgets/form_field_decoration.dart
  lib/theme/app_theme.dart
  lib/theme/constant.dart
  lib/utils/keyboard_manager.dart
Labels: type : feature, #authentication

#51 [#8] [UI] As a user, if I fail to log in, I see an error popup
  lib/l10n/app_en.arb
  lib/main.dart
  lib/screens/login/login_form.dart
  lib/screens/widgets/alert_dialog.dart
Labels: type : feature, #authentication

#53 Release - 0.3.0
  android/app/build.gradle
  assets/images/1.5x/nimble_logo_white.png
  assets/images/2.0x/nimble_logo_white.png
  assets/images/3.0x/nimble_logo_white.png
  assets/images/4.0x/nimble_logo_white.png
  integration_test/my_home_page_test.dart
  ios/Podfile.lock
  lib/api/api_service.dart
  lib/api/exception/network_exceptions.dart
  lib/api/repository/login_repository.dart
  lib/di/provider/dio_provider.dart
  lib/l10n/app_en.arb
  lib/main.dart
  lib/model/request/login_request.dart
  lib/model/response/login_attributes_response.dart
  lib/model/response/login_response.dart
  lib/screens/login/login.dart
  lib/screens/login/login_form.dart
  lib/screens/login/login_screen.dart
  lib/screens/splash/splash.dart
  lib/screens/widgets/alert_dialog.dart
  lib/screens/widgets/blur_image.dart
  lib/screens/widgets/form_field_decoration.dart
  lib/theme/app_theme.dart
  lib/theme/constant.dart
  lib/utils/keyboard_manager.dart
  pubspec.lock
  pubspec.yaml
  test/api/repository/login_repository_test.dart
  test/mocks/mock_util.dart
Labels: type : release

#54 [Chore] Bump version to 0.4.0
  pubspec.yaml
Labels: type : chore

#52 [#9] [Feature] [Part 2] Backend implementation for sign in
  lib/api/repository/credential_repository.dart
  lib/model/login_parameters.dart
  lib/usecases/login_use_case.dart
  test/api/repository/credential_repository_test.dart
  test/api/repository/login_repository_test.dart
  test/mocks/generate_mocks.dart
  test/usecases/login_use_case_test.dart
Labels: type : feature, #authentication, @0.3.0, @0.4.0

#56 [#14] [Feature] [Part 2] Implement home screen UI
  assets/images/1.5x/ic_nav_next.png
  assets/images/2.0x/ic_nav_next.png
  assets/images/3.0x/ic_nav_next.png
  assets/images/4.0x/ic_nav_next.png
  assets/images/ic_nav_next.png
  assets/images/image_overlay.png
  lib/l10n/app_en.arb
  lib/model/profile_model.dart
  lib/model/survey_model.dart
  lib/screens/home/home_screen.dart
  lib/screens/home/home_view_model.dart
  lib/theme/constant.dart
  pubspec.lock
  pubspec.yaml
Labels: type : feature, #survey-list, @0.4.0

#59 [Chore] Bump version to 0.5.0
  pubspec.yaml
Labels: type : chore

#58 Release - 0.4.0
  assets/images/1.5x/ic_nav_next.png
  assets/images/2.0x/ic_nav_next.png
  assets/images/3.0x/ic_nav_next.png
  assets/images/4.0x/ic_nav_next.png
  assets/images/ic_nav_next.png
  assets/images/image_overlay.png
  lib/api/repository/credential_repository.dart
  lib/l10n/app_en.arb
  lib/main.dart
  lib/model/login_parameters.dart
  lib/model/profile_model.dart
  lib/model/survey_model.dart
  lib/screens/home/home_screen.dart
  lib/screens/home/home_shimmer_loading.dart
  lib/screens/home/home_view_model.dart
  lib/screens/home/shimmer_circle.dart
  lib/screens/home/shimmer_rounded_rectangle.dart
  lib/theme/constant.dart
  lib/usecases/login_use_case.dart
  pubspec.lock
  pubspec.yaml
  test/api/repository/credential_repository_test.dart
  test/api/repository/login_repository_test.dart
  test/mocks/generate_mocks.dart
  test/usecases/login_use_case_test.dart
Labels: type : release
